#ifndef TAFFO_TRANSFORMS_DATATYPEINITIALIZATION_H
#define TAFFO_TRANSFORMS_DATATYPEINITIALIZATION_H

#include "mlir/Pass/Pass.h"

namespace mlir::taffo
{
#define GEN_PASS_DECL_DATATYPEINITIALIZATIONPASS
#include "Taffo/Transforms/Passes.h.inc"

}


#endif //  TAFFO_TRANSFORMS_DATATYPEINITIALIZATION_H
