#ifndef TAFFO_TRANSFORMS_DATATYPEOPTIMIZATIONPASS_H
#define TAFFO_TRANSFORMS_DATATYPEOPTIMIZATIONPASS_H

#include "mlir/Pass/Pass.h"

namespace mlir::taffo
{
#define GEN_PASS_DECL_DATATYPEOPTIMIZATIONPASS
#include "Taffo/Transforms/Passes.h.inc"

}


#endif //  TAFFO_TRANSFORMS_DATATYPEOPTIMIZATIONPASS_H
